// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingManagement.Data;

#nullable disable

namespace ParkingManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("ParkingManagement.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime?>("BookingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("BOOKING_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpectedArrival")
                        .HasColumnType("datetime")
                        .HasColumnName("EXPECTED_ARRIVAL");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("EXPIRED_AT");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOTES");

                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SLOT_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDING','CONFIRMED','CANCELLED','COMPLETED')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_ID");

                    b.Property<string>("VehicleUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("VEHICLE_USER_ID");

                    b.HasKey("BookingId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VehicleUserId" }, "FK_BOOKING_OWNER");

                    b.HasIndex(new[] { "SlotId" }, "FK_BOOKING_SLOT");

                    b.HasIndex(new[] { "VehicleId" }, "FK_BOOKING_VEHICLE");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.FloorZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZONE_ID");

                    b.Property<string>("BuildingId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("BUILDING_ID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("CAPACITY");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("FLOOR_NUMBER");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVE','MAINTENANCE')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_TYPE_ID");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ZONE_NAME");

                    b.HasKey("ZoneId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingId" }, "FK_ZONE_BUILDING");

                    b.HasIndex(new[] { "VehicleTypeId" }, "FK_ZONE_TYPE");

                    b.ToTable("floor_zone", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.IncidentLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOG_ID");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CUSTOMER_EMAIL");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CUSTOMER_PHONE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("enum('LOST_TICKET','WRONG_SLOT','SYSTEM_ERROR','OTHER')")
                        .HasColumnName("ISSUE_TYPE");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PAYMENT_ID");

                    b.Property<DateTime?>("ReportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("REPORT_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("REPORTED_BY");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("RESOLVED_AT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RESOLVED_BY");

                    b.Property<string>("SessionId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SESSION_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('OPEN','RESOLVED')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'OPEN'");

                    b.HasKey("LogId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PaymentId" }, "FK_INCIDENT_PAYMENT");

                    b.HasIndex(new[] { "SessionId" }, "FK_INCIDENT_SESSION");

                    b.HasIndex(new[] { "ResolvedBy" }, "FK_INCIDENT_STAFF");

                    b.HasIndex(new[] { "ReportedBy" }, "FK_INCIDENT_USER");

                    b.ToTable("incident_log", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.MonthlyPass", b =>
                {
                    b.Property<int>("MonthlyPassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MONTHLY_PASS_ID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("END_DATE");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDING','PAID')")
                        .HasColumnName("PAYMENT_STATUS")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<string>("PlanId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PLAN_ID");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVE','EXPIRED')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_ID");

                    b.HasKey("MonthlyPassId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PlanId" }, "FK_MONTHLYPASS_PLAN");

                    b.HasIndex(new[] { "VehicleId" }, "FK_MONTHLYPASS_VEHICLE");

                    b.ToTable("monthly_pass", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingBuilding", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("BUILDING_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("BUILDING_NAME");

                    b.Property<bool?>("Is247")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_24_7")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVE','MAINTENANCE','CLOSED')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<int>("TotalFloors")
                        .HasColumnType("int")
                        .HasColumnName("TOTAL_FLOORS");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("int")
                        .HasColumnName("TOTAL_SLOTS");

                    b.Property<string>("WeekdayHours")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("WEEKDAY_HOURS");

                    b.Property<string>("WeekendHours")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("WEEKEND_HOURS");

                    b.HasKey("BuildingId")
                        .HasName("PRIMARY");

                    b.ToTable("parking_building", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SESSION_ID");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BOOKING_ID");

                    b.Property<string>("CameraIn")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CAMERA_IN");

                    b.Property<string>("CameraOut")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CAMERA_OUT");

                    b.Property<DateTime?>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CHECK_IN_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CHECK_OUT_TIME");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("DURATION_MINUTES");

                    b.Property<string>("GateIn")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GATE_IN");

                    b.Property<string>("GateOut")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GATE_OUT");

                    b.Property<string>("ImageUrlIn")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IMAGE_URL_IN");

                    b.Property<string>("ImageUrlOut")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("IMAGE_URL_OUT");

                    b.Property<string>("LicensePlateIn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LICENSE_PLATE_IN");

                    b.Property<string>("LicensePlateOut")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LICENSE_PLATE_OUT");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDING','PAID','FAILED')")
                        .HasColumnName("PAYMENT_STATUS")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SLOT_ID");

                    b.Property<string>("StaffInId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STAFF_IN_ID");

                    b.Property<string>("StaffOutId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STAFF_OUT_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVE','COMPLETED','CANCELLED','LOST_TICKET')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<decimal?>("TotalFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("TOTAL_FEE");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_ID");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_TYPE_ID");

                    b.HasKey("SessionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookingId" }, "FK_SESSION_BOOKING");

                    b.HasIndex(new[] { "SlotId" }, "FK_SESSION_SLOT");

                    b.HasIndex(new[] { "StaffInId" }, "FK_SESSION_STAFF_IN");

                    b.HasIndex(new[] { "StaffOutId" }, "FK_SESSION_STAFF_OUT");

                    b.HasIndex(new[] { "VehicleTypeId" }, "FK_SESSION_TYPE");

                    b.HasIndex(new[] { "VehicleId" }, "FK_SESSION_VEHICLE");

                    b.ToTable("parking_session", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingSlot", b =>
                {
                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SLOT_ID");

                    b.Property<string>("CurrentSessionId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CURRENT_SESSION_ID");

                    b.Property<bool?>("IsElectricCharging")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ELECTRIC_CHARGING")
                        .HasDefaultValueSql("'0'");

                    b.Property<bool?>("IsHandicap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_HANDICAP")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("LAST_UPDATED")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SLOT_NAME");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'AVAILABLE'");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZONE_ID");

                    b.HasKey("SlotId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ZoneId" }, "FK_SLOT_ZONE");

                    b.ToTable("parking_slot", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PAYMENT_ID");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("AMOUNT_DUE");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("AMOUNT_PAID");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BOOKING_ID");

                    b.Property<int?>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CARD_ID");

                    b.Property<decimal?>("ChangeDue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CHANGE_DUE")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("enum('CASH','VNPAY','SUBSCRIPTION')")
                        .HasColumnName("PAYMENT_METHOD");

                    b.Property<DateTime?>("PaymentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("PAYMENT_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("enum('SESSION','MONTHLY_PASS','BOOKING','INCIDENT')")
                        .HasColumnName("PAYMENT_TYPE");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("RECEIPT_URL");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("SessionId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SESSION_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('SUCCESS','FAILED')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'SUCCESS'");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TRANSACTION_ID");

                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("USER_ID");

                    b.HasKey("PaymentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookingId" }, "FK_PAY_BOOKING");

                    b.HasIndex(new[] { "CardId" }, "FK_PAY_CARD");

                    b.HasIndex(new[] { "SessionId" }, "FK_PAY_SESSION");

                    b.HasIndex(new[] { "UserId" }, "FK_PAY_USER");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.PricingPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POLICY_ID");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("BASE_PRICE");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("EFFECTIVE_DATE");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("HOURLY_RATE");

                    b.Property<decimal>("OvernightFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OVERNIGHT_FEE");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_TYPE_ID");

                    b.HasKey("PolicyId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VehicleTypeId" }, "FK_POLICY_TYPE");

                    b.ToTable("pricing_policy", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleName" }, "ROLE_NAME")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.SlotStatusLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("changed_by");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("old_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("slot_id");

                    b.HasKey("LogId");

                    b.ToTable("SLOT_STATUS_LOGS", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.SubscriptionPlan", b =>
                {
                    b.Property<string>("PlanId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PLAN_ID");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("DURATION_DAYS");

                    b.Property<int?>("GracePeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GRACE_PERIOD_DAYS")
                        .HasDefaultValueSql("'0'");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_TYPE_ID");

                    b.HasKey("PlanId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VehicleTypeId" }, "FK_PLAN_TYPE");

                    b.ToTable("subscription_plan", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_AT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FULL_NAME");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("LAST_LOGIN");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PHONE");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVE','INACTIVE','BANNED')")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "EMAIL")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "FK_USER_ROLE");

                    b.HasIndex(new[] { "Username" }, "USERNAME")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_ID");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BRAND");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("COLOR");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MODEL");

                    b.Property<string>("VehicleDescription")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("VEHICLE_DESCRIPTION");

                    b.Property<string>("VehiclePlateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("VEHICLE_PLATE_NUMBER");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_TYPE_ID");

                    b.Property<string>("VehicleUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("VEHICLE_USER_ID");

                    b.HasKey("VehicleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VehicleUserId" }, "FK_VEHICLE_OWNER");

                    b.HasIndex(new[] { "VehicleTypeId" }, "FK_VEHICLE_TYPE");

                    b.HasIndex(new[] { "VehiclePlateNumber" }, "VEHICLE_PLATE_NUMBER")
                        .IsUnique();

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VEHICLE_TYPE_ID");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("VEHICLE_TYPE_NAME");

                    b.HasKey("VehicleTypeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VehicleTypeName" }, "VEHICLE_TYPE_NAME")
                        .IsUnique();

                    b.ToTable("vehicle_type", (string)null);
                });

            modelBuilder.Entity("ParkingManagement.Models.Booking", b =>
                {
                    b.HasOne("ParkingManagement.Models.ParkingSlot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .HasConstraintName("FK_BOOKING_SLOT");

                    b.HasOne("ParkingManagement.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_BOOKING_VEHICLE");

                    b.HasOne("ParkingManagement.Models.User", "VehicleUser")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleUserId")
                        .IsRequired()
                        .HasConstraintName("FK_BOOKING_OWNER");

                    b.Navigation("Slot");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleUser");
                });

            modelBuilder.Entity("ParkingManagement.Models.FloorZone", b =>
                {
                    b.HasOne("ParkingManagement.Models.ParkingBuilding", "Building")
                        .WithMany("FloorZones")
                        .HasForeignKey("BuildingId")
                        .HasConstraintName("FK_ZONE_BUILDING");

                    b.HasOne("ParkingManagement.Models.VehicleType", "VehicleType")
                        .WithMany("FloorZones")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ZONE_TYPE");

                    b.Navigation("Building");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingManagement.Models.IncidentLog", b =>
                {
                    b.HasOne("ParkingManagement.Models.Payment", "Payment")
                        .WithMany("IncidentLogs")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_INCIDENT_PAYMENT");

                    b.HasOne("ParkingManagement.Models.User", "ReportedByNavigation")
                        .WithMany("IncidentLogReportedByNavigations")
                        .HasForeignKey("ReportedBy")
                        .IsRequired()
                        .HasConstraintName("FK_INCIDENT_USER");

                    b.HasOne("ParkingManagement.Models.User", "ResolvedByNavigation")
                        .WithMany("IncidentLogResolvedByNavigations")
                        .HasForeignKey("ResolvedBy")
                        .HasConstraintName("FK_INCIDENT_STAFF");

                    b.HasOne("ParkingManagement.Models.ParkingSession", "Session")
                        .WithMany("IncidentLogs")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_INCIDENT_SESSION");

                    b.Navigation("Payment");

                    b.Navigation("ReportedByNavigation");

                    b.Navigation("ResolvedByNavigation");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingManagement.Models.MonthlyPass", b =>
                {
                    b.HasOne("ParkingManagement.Models.SubscriptionPlan", "Plan")
                        .WithMany("MonthlyPasses")
                        .HasForeignKey("PlanId")
                        .HasConstraintName("FK_MONTHLYPASS_PLAN");

                    b.HasOne("ParkingManagement.Models.Vehicle", "Vehicle")
                        .WithMany("MonthlyPasses")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_MONTHLYPASS_VEHICLE");

                    b.Navigation("Plan");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingSession", b =>
                {
                    b.HasOne("ParkingManagement.Models.Booking", "Booking")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_SESSION_BOOKING");

                    b.HasOne("ParkingManagement.Models.ParkingSlot", "Slot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SlotId")
                        .HasConstraintName("FK_SESSION_SLOT");

                    b.HasOne("ParkingManagement.Models.User", "StaffIn")
                        .WithMany("ParkingSessionStaffIns")
                        .HasForeignKey("StaffInId")
                        .HasConstraintName("FK_SESSION_STAFF_IN");

                    b.HasOne("ParkingManagement.Models.User", "StaffOut")
                        .WithMany("ParkingSessionStaffOuts")
                        .HasForeignKey("StaffOutId")
                        .HasConstraintName("FK_SESSION_STAFF_OUT");

                    b.HasOne("ParkingManagement.Models.Vehicle", "Vehicle")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_SESSION_VEHICLE");

                    b.HasOne("ParkingManagement.Models.VehicleType", "VehicleType")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_SESSION_TYPE");

                    b.Navigation("Booking");

                    b.Navigation("Slot");

                    b.Navigation("StaffIn");

                    b.Navigation("StaffOut");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingSlot", b =>
                {
                    b.HasOne("ParkingManagement.Models.FloorZone", "Zone")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK_SLOT_ZONE");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("ParkingManagement.Models.Payment", b =>
                {
                    b.HasOne("ParkingManagement.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_PAY_BOOKING");

                    b.HasOne("ParkingManagement.Models.MonthlyPass", "Card")
                        .WithMany("Payments")
                        .HasForeignKey("CardId")
                        .HasConstraintName("FK_PAY_CARD");

                    b.HasOne("ParkingManagement.Models.ParkingSession", "Session")
                        .WithMany("Payments")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_PAY_SESSION");

                    b.HasOne("ParkingManagement.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_PAY_USER");

                    b.Navigation("Booking");

                    b.Navigation("Card");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingManagement.Models.PricingPolicy", b =>
                {
                    b.HasOne("ParkingManagement.Models.VehicleType", "VehicleType")
                        .WithMany("PricingPolicies")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_POLICY_TYPE");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingManagement.Models.SubscriptionPlan", b =>
                {
                    b.HasOne("ParkingManagement.Models.VehicleType", "VehicleType")
                        .WithMany("SubscriptionPlans")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PLAN_TYPE");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ParkingManagement.Models.User", b =>
                {
                    b.HasOne("ParkingManagement.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_USER_ROLE");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ParkingManagement.Models.Vehicle", b =>
                {
                    b.HasOne("ParkingManagement.Models.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_TYPE");

                    b.HasOne("ParkingManagement.Models.User", "VehicleUser")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleUserId")
                        .IsRequired()
                        .HasConstraintName("FK_VEHICLE_OWNER");

                    b.Navigation("VehicleType");

                    b.Navigation("VehicleUser");
                });

            modelBuilder.Entity("ParkingManagement.Models.Booking", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ParkingManagement.Models.FloorZone", b =>
                {
                    b.Navigation("ParkingSlots");
                });

            modelBuilder.Entity("ParkingManagement.Models.MonthlyPass", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingBuilding", b =>
                {
                    b.Navigation("FloorZones");
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingSession", b =>
                {
                    b.Navigation("IncidentLogs");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ParkingManagement.Models.ParkingSlot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ParkingSessions");
                });

            modelBuilder.Entity("ParkingManagement.Models.Payment", b =>
                {
                    b.Navigation("IncidentLogs");
                });

            modelBuilder.Entity("ParkingManagement.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ParkingManagement.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("MonthlyPasses");
                });

            modelBuilder.Entity("ParkingManagement.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("IncidentLogReportedByNavigations");

                    b.Navigation("IncidentLogResolvedByNavigations");

                    b.Navigation("ParkingSessionStaffIns");

                    b.Navigation("ParkingSessionStaffOuts");

                    b.Navigation("Payments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ParkingManagement.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MonthlyPasses");

                    b.Navigation("ParkingSessions");
                });

            modelBuilder.Entity("ParkingManagement.Models.VehicleType", b =>
                {
                    b.Navigation("FloorZones");

                    b.Navigation("ParkingSessions");

                    b.Navigation("PricingPolicies");

                    b.Navigation("SubscriptionPlans");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
