-- ============================================================
-- DATABASE PARKING MANAGEMENT SYSTEM
-- ============================================================

-- ============================================================
-- NHÓM 1: QUẢN LÝ NGƯỜI DÙNG & PHÂN QUYỀN
-- ============================================================

CREATE TABLE ROLE (
    ROLE_ID     INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME   VARCHAR(50) UNIQUE NOT NULL, -- SystemAdmin / ParkingManager / ParkingStaff / ParkingUser
    DESCRIPTION VARCHAR(200)
);

CREATE TABLE USERS (
    USER_ID     VARCHAR(20) PRIMARY KEY,
    USERNAME    VARCHAR(50) UNIQUE NOT NULL,                 
    PASSWORD    VARCHAR(255) NOT NULL,               
    FULL_NAME   VARCHAR(100),
    EMAIL       VARCHAR(100) UNIQUE,
    PHONE       VARCHAR(15),
    ROLE_ID     INT,                         
    STATUS      ENUM('ACTIVE','INACTIVE','BANNED') DEFAULT 'ACTIVE', 
    LAST_LOGIN  DATETIME,                                                            
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

-- ============================================================
-- NHÓM 2: QUẢN LÝ PHƯƠNG TIỆN & CHỦ XE
-- ============================================================

CREATE TABLE VEHICLE_TYPE (
    VEHICLE_TYPE_ID       INT AUTO_INCREMENT PRIMARY KEY, 
    VEHICLE_TYPE_NAME     VARCHAR(100) UNIQUE NOT NULL    
);

CREATE TABLE VEHICLE (
    VEHICLE_ID           INT AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_PLATE_NUMBER VARCHAR(50) NOT NULL UNIQUE, 
    VEHICLE_DESCRIPTION  VARCHAR(200), --
    BRAND                VARCHAR(50),                 
    MODEL                VARCHAR(50),                 
    COLOR                VARCHAR(30),                                                    
    VEHICLE_TYPE_ID      INT NOT NULL,                
    VEHICLE_USER_ID      VARCHAR(20) NOT NULL, --userID
    
    CONSTRAINT FK_VEHICLE_TYPE FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID), 
    CONSTRAINT FK_VEHICLE_OWNER FOREIGN KEY (VEHICLE_USER_ID) REFERENCES USERS(USER_ID)
);

-- ============================================================
-- NHÓM 3: QUẢN LÝ TOÀ NHÀ & BÃI ĐỖ
-- ============================================================

CREATE TABLE PARKING_BUILDING (
    BUILDING_ID         VARCHAR(10) PRIMARY KEY,
    BUILDING_NAME       VARCHAR(200) NOT NULL,
    ADDRESS             VARCHAR(500),
    TOTAL_FLOORS        INT NOT NULL,
    TOTAL_SLOTS         INT NOT NULL,
    WEEKDAY_HOURS       VARCHAR(20),                 
    WEEKEND_HOURS       VARCHAR(20),
    IS_24_7             BOOLEAN DEFAULT FALSE,
    STATUS              ENUM('ACTIVE','MAINTENANCE','CLOSED') DEFAULT 'ACTIVE'
);

CREATE TABLE FLOOR_ZONE (
    ZONE_ID         INT AUTO_INCREMENT PRIMARY KEY,
    ZONE_NAME       VARCHAR(50) NOT NULL,     -- Khu A, B, C (API §3.2)
    FLOOR_NUMBER    INT NOT NULL,             -- Tầng 1, 2, 3 (API §3.2)
    CAPACITY        INT NOT NULL,
    STATUS          ENUM('ACTIVE','MAINTENANCE') DEFAULT 'ACTIVE',
    VEHICLE_TYPE_ID INT NOT NULL,
    BUILDING_ID     VARCHAR(10),                             
    CONSTRAINT FK_ZONE_TYPE     FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID), 
    CONSTRAINT FK_ZONE_BUILDING FOREIGN KEY (BUILDING_ID)     REFERENCES PARKING_BUILDING(BUILDING_ID)
);

CREATE TABLE PARKING_SLOT (
    SLOT_ID                 VARCHAR(20) PRIMARY KEY,
    SLOT_NAME               VARCHAR(20) NOT NULL,   -- Ví dụ: "A101" --**
    STATUS                  ENUM('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE') DEFAULT 'AVAILABLE',
    IS_HANDICAP             BOOLEAN DEFAULT FALSE,   
    IS_ELECTRIC_CHARGING    BOOLEAN DEFAULT FALSE,   
    CURRENT_SESSION_ID      VARCHAR(20),                     
    LAST_UPDATED            DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    ZONE_ID                 INT NOT NULL,                
    CONSTRAINT FK_SLOT_ZONE FOREIGN KEY (ZONE_ID) REFERENCES FLOOR_ZONE(ZONE_ID)
);

-- ============================================================
-- NHÓM 4: ĐẶT CHỖ & PHIÊN ĐỖ XE
-- ============================================================

CREATE TABLE BOOKING (
    BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_USER_ID VARCHAR(20) NOT NULL, 
    VEHICLE_ID     INT , 
    SLOT_ID VARCHAR(20),
    EXPECTED_ARRIVAL DATETIME NOT NULL,
    EXPIRED_AT DATETIME,
    BOOKING_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') DEFAULT 'PENDING',
    NOTES VARCHAR(255),
    
    CONSTRAINT FK_BOOKING_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID),
    CONSTRAINT FK_BOOKING_OWNER FOREIGN KEY (VEHICLE_USER_ID) REFERENCES USERS(USER_ID), 
    CONSTRAINT FK_BOOKING_SLOT FOREIGN KEY (SLOT_ID) REFERENCES PARKING_SLOT(SLOT_ID)
);

CREATE TABLE PARKING_SESSION (
    SESSION_ID          VARCHAR(20) PRIMARY KEY,               
    CHECK_IN_TIME       DATETIME DEFAULT CURRENT_TIMESTAMP,
    CHECK_OUT_TIME      DATETIME,
    DURATION_MINUTES    INT,
    -- Dữ liệu nhận diện khi VÀO
    LICENSE_PLATE_IN    VARCHAR(50) NOT NULL,
    IMAGE_URL_IN        VARCHAR(500),
    CAMERA_IN           VARCHAR(50),
    GATE_IN             VARCHAR(50),
    STAFF_IN_ID         VARCHAR(20),
    -- Dữ liệu nhận diện khi RA
    LICENSE_PLATE_OUT   VARCHAR(50),
    IMAGE_URL_OUT       VARCHAR(500),     
    GATE_OUT            VARCHAR(50),                     
    CAMERA_OUT          VARCHAR(50),
    STAFF_OUT_ID        VARCHAR(20),
    -- Trạng thái & Tiền bạc
    TOTAL_FEE           DECIMAL(10,2),              
    STATUS              ENUM('ACTIVE','COMPLETED','CANCELLED','LOST_TICKET') DEFAULT 'ACTIVE', 
    PAYMENT_STATUS      ENUM('PENDING','PAID','FAILED') DEFAULT 'PENDING',
    -- Liên kết quan hệ 
    VEHICLE_TYPE_ID     INT NOT NULL,
    SLOT_ID             VARCHAR(20),
    VEHICLE_ID          INT,
    BOOKING_ID          INT,
                     
    CONSTRAINT FK_SESSION_TYPE     FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID), 
    CONSTRAINT FK_SESSION_SLOT     FOREIGN KEY (SLOT_ID)         REFERENCES PARKING_SLOT(SLOT_ID),
    CONSTRAINT FK_SESSION_VEHICLE  FOREIGN KEY (VEHICLE_ID)      REFERENCES VEHICLE(VEHICLE_ID),
    CONSTRAINT FK_SESSION_BOOKING  FOREIGN KEY (BOOKING_ID)      REFERENCES BOOKING(BOOKING_ID),
    CONSTRAINT FK_SESSION_STAFF_IN  FOREIGN KEY (STAFF_IN_ID)   REFERENCES USERS(USER_ID),
    CONSTRAINT FK_SESSION_STAFF_OUT FOREIGN KEY (STAFF_OUT_ID)  REFERENCES USERS(USER_ID)
);
-- Bảng danh mục Gói cước tháng để khớp nối
CREATE TABLE SUBSCRIPTION_PLAN (
    PLAN_ID             VARCHAR(50) PRIMARY KEY,      -- Ví dụ: "plan_monthly_car" 
    VEHICLE_TYPE_ID     INT NOT NULL,
    DURATION_DAYS       INT NOT NULL,                 -- 30 ngày
    PRICE               DECIMAL(10,2) NOT NULL,       -- 1,500,000 VND
    GRACE_PERIOD_DAYS   INT DEFAULT 0,                -- Số ngày gia hạn (7 days)
    CONSTRAINT FK_PLAN_TYPE FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID)
);

-- ============================================================
-- NHÓM 5: BẢNG GIÁ & THẺ THÁNG
-- ============================================================

CREATE TABLE PRICING_POLICY (
    POLICY_ID           INT AUTO_INCREMENT PRIMARY KEY,
    BASE_PRICE          DECIMAL(10,2) NOT NULL,
    HOURLY_RATE         DECIMAL(10,2) NOT NULL,
    OVERNIGHT_FEE       DECIMAL(10,2) NOT NULL,
    EFFECTIVE_DATE      DATE NOT NULL,
    VEHICLE_TYPE_ID     INT NOT NULL,
    CONSTRAINT FK_POLICY_TYPE FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID) 
);

CREATE TABLE MONTHLY_PASS (
    MONTHLY_PASS_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEHICLE_ID      INT NOT NULL,
    PLAN_ID         VARCHAR(50),
    START_DATE      DATE NOT NULL,
    END_DATE        DATE NOT NULL,
    STATUS          ENUM('ACTIVE', 'EXPIRED') DEFAULT 'ACTIVE',
    PAYMENT_STATUS  ENUM('PENDING','PAID') DEFAULT 'PENDING',
    CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,   --
    CONSTRAINT FK_MONTHLYPASS_PLAN FOREIGN KEY (PLAN_ID) REFERENCES SUBSCRIPTION_PLAN(PLAN_ID),
    CONSTRAINT FK_MONTHLYPASS_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
);

-- ============================================================
-- NHÓM 6: THANH TOÁN
-- ============================================================

CREATE TABLE PAYMENT (
    PAYMENT_ID      VARCHAR(20) PRIMARY KEY,
    PAYMENT_TYPE    ENUM('SESSION','MONTHLY_PASS','BOOKING','INCIDENT') NOT NULL,
    AMOUNT_DUE      DECIMAL(10,2) NOT NULL,
    AMOUNT_PAID     DECIMAL(10,2) NOT NULL,
    CHANGE_DUE      DECIMAL(10,2) DEFAULT 0,         
    PAYMENT_METHOD  ENUM('CASH','VNPAY','SUBSCRIPTION') NOT NULL, 
    PAYMENT_TIME    DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS          ENUM('SUCCESS','FAILED') DEFAULT 'SUCCESS',   
    TRANSACTION_ID  VARCHAR(100),                    
    RECEIPT_URL     VARCHAR(500),                    
    REMARKS         VARCHAR(255),
    SESSION_ID      VARCHAR(20),
    CARD_ID         INT,
    BOOKING_ID      INT,
    USER_ID         VARCHAR(20),                     
    
    CONSTRAINT FK_PAY_SESSION  FOREIGN KEY (SESSION_ID)  REFERENCES PARKING_SESSION(SESSION_ID),
    CONSTRAINT FK_PAY_CARD     FOREIGN KEY (CARD_ID)     REFERENCES MONTHLY_PASS(MONTHLY_PASS_ID),
    CONSTRAINT FK_PAY_BOOKING  FOREIGN KEY (BOOKING_ID)  REFERENCES BOOKING(BOOKING_ID),
    CONSTRAINT FK_PAY_USER     FOREIGN KEY (USER_ID)     REFERENCES USERS(USER_ID)
);

-- ============================================================
-- NHÓM 7: SỰ CỐ & VÉ MẤT
-- ============================================================

CREATE TABLE INCIDENT_LOG (
    LOG_ID          INT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID      VARCHAR(20),
    REPORTED_BY     VARCHAR(20) NOT NULL,            
    ISSUE_TYPE      ENUM('LOST_TICKET','WRONG_SLOT','SYSTEM_ERROR','OTHER') NOT NULL,
    DESCRIPTION     VARCHAR(500),
    REPORT_TIME     DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS          ENUM('OPEN','RESOLVED') DEFAULT 'OPEN',
    CUSTOMER_PHONE  VARCHAR(15),                     
    CUSTOMER_EMAIL  VARCHAR(100),
    PAYMENT_ID      VARCHAR(20),
    RESOLVED_BY     VARCHAR(20),                     
    RESOLVED_AT     DATETIME,   
    
    CONSTRAINT FK_INCIDENT_SESSION FOREIGN KEY (SESSION_ID)   REFERENCES PARKING_SESSION(SESSION_ID),
    CONSTRAINT FK_INCIDENT_USER   FOREIGN KEY (REPORTED_BY)  REFERENCES USERS(USER_ID),
    CONSTRAINT FK_INCIDENT_STAFF   FOREIGN KEY (RESOLVED_BY)  REFERENCES USERS(USER_ID),
    CONSTRAINT FK_INCIDENT_PAYMENT   FOREIGN KEY (PAYMENT_ID)  REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE SLOT_STATUS_LOGS (
    log_id VARCHAR(50) NOT NULL,
    slot_id VARCHAR(50) NOT NULL,
    old_status VARCHAR(20) NOT NULL,
    new_status VARCHAR(20) NOT NULL,
    changed_by VARCHAR(50) NOT NULL,
    changed_at DATETIME NOT NULL,
    reason NVARCHAR(255) NULL,
    estimated_duration_minutes INT NULL,
    CONSTRAINT pk_slot_status_logs PRIMARY KEY (log_id)
);
