-- ============================================================
-- DATABASE PARKING MANAGEMENT SYSTEM (UPDATED)
-- ============================================================

-- ============================================================
-- NHÓM 1: QUẢN LÝ NGƯỜI DÙNG & PHÂN QUYỀN
-- ============================================================

CREATE TABLE ROLE (
    ROLE_ID     INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME   VARCHAR(50) UNIQUE NOT NULL, -- SystemAdmin / ParkingManager / ParkingStaff / ParkingUser
    DESCRIPTION VARCHAR(200)
);

CREATE TABLE USERS (
    USER_ID     VARCHAR(36) PRIMARY KEY,
    USERNAME    VARCHAR(50) UNIQUE NOT NULL,                 
    PASSWORD    VARCHAR(255) NOT NULL,               
    FULL_NAME   VARCHAR(100),
    EMAIL       VARCHAR(100) UNIQUE,
    PHONE       VARCHAR(15),
    ROLE_ID     INT,                                         
    STATUS      ENUM('ACTIVE','INACTIVE','BANNED') DEFAULT 'ACTIVE', 
    LAST_LOGIN  DATETIME,                                                                                   
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    AvatarUrl   LONGTEXT,

    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

-- ============================================================
-- NHÓM 2: DANH MỤC PHƯƠNG TIỆN
-- ============================================================

CREATE TABLE VEHICLE_TYPE (
    VEHICLE_TYPE_ID       INT AUTO_INCREMENT PRIMARY KEY, 
    VEHICLE_TYPE_NAME     VARCHAR(100) UNIQUE NOT NULL    
);

-- ============================================================
-- NHÓM 3: QUẢN LÝ TOÀ NHÀ & BÃI ĐỖ
-- ============================================================

CREATE TABLE PARKING_BUILDING (
    BUILDING_ID         VARCHAR(10) PRIMARY KEY,
    BUILDING_NAME       VARCHAR(200) NOT NULL,
    ADDRESS             VARCHAR(500),
    TOTAL_FLOORS        INT NOT NULL,
    TOTAL_SLOTS         INT NOT NULL,
    WEEKDAY_HOURS       VARCHAR(20),                 
    WEEKEND_HOURS       VARCHAR(20),
    IS_24_7             BOOLEAN DEFAULT FALSE,
    STATUS              ENUM('ACTIVE','MAINTENANCE','CLOSED') DEFAULT 'ACTIVE'
);

CREATE TABLE FLOOR_ZONE (
    ZONE_ID             INT AUTO_INCREMENT PRIMARY KEY,
    ZONE_NAME           VARCHAR(50) NOT NULL,
    FLOOR_NUMBER        INT NOT NULL,
    CAPACITY            INT NOT NULL,
    AVAILABLE_CAPACITY  INT NOT NULL DEFAULT 0 COMMENT 'Số chỗ trống thực tế hiện tại. Giảm khi check-in, tăng khi check-out.',
    STATUS              ENUM('ACTIVE','MAINTENANCE') DEFAULT 'ACTIVE',
    VEHICLE_TYPE_ID     INT NOT NULL,
    BUILDING_ID         VARCHAR(10),
    CONSTRAINT FK_ZONE_TYPE     FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID),
    CONSTRAINT FK_ZONE_BUILDING FOREIGN KEY (BUILDING_ID)     REFERENCES PARKING_BUILDING(BUILDING_ID)
);

CREATE TABLE PARKING_SLOT (
    SLOT_ID                 VARCHAR(20) PRIMARY KEY,
    SLOT_NAME               VARCHAR(20) NOT NULL,   
    STATUS                  ENUM('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE') DEFAULT 'AVAILABLE',
    IS_HANDICAP             BOOLEAN DEFAULT FALSE,   
    IS_ELECTRIC_CHARGING    BOOLEAN DEFAULT FALSE,   
    CURRENT_SESSION_ID      VARCHAR(20),                     
    LAST_UPDATED            DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    ZONE_ID                 INT NOT NULL,                
    CONSTRAINT FK_SLOT_ZONE FOREIGN KEY (ZONE_ID) REFERENCES FLOOR_ZONE(ZONE_ID)
);

-- ============================================================
-- NHÓM 4: ĐẶT CHỖ & PHIÊN ĐỖ XE (LƯU BIỂN SỐ TRỰC TIẾP)
-- ============================================================

CREATE TABLE BOOKING (
    BOOKING_ID      VARCHAR(20) PRIMARY KEY,
    VEHICLE_USER_ID VARCHAR(36) NOT NULL,
    LICENSE_PLATE   VARCHAR(50) NOT NULL,     -- Lưu trực tiếp biển số xe đặt trước
    VEHICLE_TYPE_ID INT NOT NULL,             -- Lưu trực tiếp loại xe để hệ thống điều phối khu vực
    ZONE_ID         INT NULL,                 -- Zone được gợi ý khi đặt chỗ (thay thế SLOT_ID)
    EXPECTED_ARRIVAL DATETIME NOT NULL,
    EXPIRED_AT      DATETIME,
    BOOKING_TIME    DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS          ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') DEFAULT 'PENDING',
    NOTES           VARCHAR(255),

    CONSTRAINT FK_BOOKING_OWNER       FOREIGN KEY (VEHICLE_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_BOOKING_ZONE        FOREIGN KEY (ZONE_ID)         REFERENCES FLOOR_ZONE(ZONE_ID),
    CONSTRAINT FK_BOOKING_VEHICLE_TYPE FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID)
);

CREATE TABLE PARKING_SESSION (
    SESSION_ID          VARCHAR(20) PRIMARY KEY,
    CHECK_IN_TIME       DATETIME DEFAULT CURRENT_TIMESTAMP,
    CHECK_OUT_TIME      DATETIME,
    DURATION_MINUTES    INT,
    -- Dữ liệu nhận diện khi VÀO
    LICENSE_PLATE_IN    VARCHAR(50) NOT NULL,
    IMAGE_URL_IN        VARCHAR(500),
    CAMERA_IN           VARCHAR(50),
    GATE_IN             VARCHAR(50),
    STAFF_IN_ID         VARCHAR(36),
    -- Dữ liệu nhận diện khi RA
    LICENSE_PLATE_OUT   VARCHAR(50),
    IMAGE_URL_OUT       VARCHAR(500),
    GATE_OUT            VARCHAR(50),
    CAMERA_OUT          VARCHAR(50),
    STAFF_OUT_ID        VARCHAR(36),
    -- Trạng thái & Tiền bạc
    TOTAL_FEE           DECIMAL(10,2),
    STATUS              ENUM('ACTIVE','COMPLETED','CANCELLED','LOST_TICKET') DEFAULT 'ACTIVE',
    PAYMENT_STATUS      ENUM('PENDING','PAID','FAILED') DEFAULT 'PENDING',
    IS_LOCKED           BOOLEAN DEFAULT FALSE,
    -- Liên kết quan hệ
    VEHICLE_TYPE_ID     INT NOT NULL,
    ZONE_ID             INT NULL,                 -- Zone nơi xe được đỗ (thay thế SLOT_ID trong luồng chính)
    SLOT_ID             VARCHAR(20) NULL,         -- Giữ lại để tương thích ngược với dữ liệu cũ
    BOOKING_ID          VARCHAR(20),
    TICKET_CODE         VARCHAR(20),

    CONSTRAINT FK_SESSION_TYPE      FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID),
    CONSTRAINT FK_SESSION_ZONE      FOREIGN KEY (ZONE_ID)         REFERENCES FLOOR_ZONE(ZONE_ID),
    CONSTRAINT FK_SESSION_SLOT      FOREIGN KEY (SLOT_ID)         REFERENCES PARKING_SLOT(SLOT_ID),
    CONSTRAINT FK_SESSION_BOOKING   FOREIGN KEY (BOOKING_ID)      REFERENCES BOOKING(BOOKING_ID),
    CONSTRAINT FK_SESSION_STAFF_IN  FOREIGN KEY (STAFF_IN_ID)     REFERENCES USERS(USER_ID),
    CONSTRAINT FK_SESSION_STAFF_OUT FOREIGN KEY (STAFF_OUT_ID)    REFERENCES USERS(USER_ID)
);

-- ============================================================
-- NHÓM 5: CHÍNH SÁCH GIÁ GIỜ/LƯỢT
-- ============================================================

CREATE TABLE PRICING_POLICY (
    POLICY_ID           INT AUTO_INCREMENT PRIMARY KEY,
    BASE_PRICE          DECIMAL(10,2) NOT NULL,
    HOURLY_RATE         DECIMAL(10,2) NOT NULL,
    OVERNIGHT_FEE       DECIMAL(10,2) NOT NULL,
    EFFECTIVE_DATE      DATE NOT NULL,
    VEHICLE_TYPE_ID     INT NOT NULL,
    HANDLING_FEE        DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_POLICY_TYPE FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID) 
);

-- ============================================================
-- NHÓM 6: THANH TOÁN (BỎ MONTHLY_PASS)
-- ============================================================

CREATE TABLE PAYMENT (
    PAYMENT_ID      VARCHAR(20) PRIMARY KEY,
    PAYMENT_TYPE    ENUM('SESSION','BOOKING','INCIDENT') NOT NULL, -- Đã bỏ MONTHLY_PASS
    AMOUNT_DUE      DECIMAL(10,2) NOT NULL,
    AMOUNT_PAID     DECIMAL(10,2) NOT NULL,
    CHANGE_DUE      DECIMAL(10,2) DEFAULT 0,         
    PAYMENT_METHOD  ENUM('CASH','VNPAY') NOT NULL,                 -- Đã bỏ SUBSCRIPTION
    PAYMENT_TIME    DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS          ENUM('SUCCESS','FAILED') DEFAULT 'SUCCESS',   
    TRANSACTION_ID  VARCHAR(100),                    
    RECEIPT_URL     VARCHAR(500),                    
    REMARKS         VARCHAR(255),
    SESSION_ID      VARCHAR(20),
    BOOKING_ID      VARCHAR(20),
    USER_ID         VARCHAR(36),                     
    
    CONSTRAINT FK_PAY_SESSION  FOREIGN KEY (SESSION_ID)  REFERENCES PARKING_SESSION(SESSION_ID),
    CONSTRAINT FK_PAY_BOOKING  FOREIGN KEY (BOOKING_ID)  REFERENCES BOOKING(BOOKING_ID),
    CONSTRAINT FK_PAY_USER     FOREIGN KEY (USER_ID)     REFERENCES USERS(USER_ID)
);

-- ============================================================
-- NHÓM 7: SỰ CỐ & NHẬT KÝ HỆ THỐNG
-- ============================================================

CREATE TABLE INCIDENT_LOG (
    LOG_ID          INT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID      VARCHAR(20),
    REPORTED_BY     VARCHAR(36) NOT NULL,            
    ISSUE_TYPE      ENUM('LOST_TICKET','WRONG_SLOT','SYSTEM_ERROR','OTHER') NOT NULL,
    DESCRIPTION     VARCHAR(500),
    REPORT_TIME     DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS          ENUM('OPEN','RESOLVED') DEFAULT 'OPEN',
    CUSTOMER_PHONE  VARCHAR(15),                     
    CUSTOMER_EMAIL  VARCHAR(100),
    PAYMENT_ID      VARCHAR(20),
    RESOLVED_BY     VARCHAR(36),                     
    RESOLVED_AT     DATETIME,   
    
    CONSTRAINT FK_INCIDENT_SESSION FOREIGN KEY (SESSION_ID)   REFERENCES PARKING_SESSION(SESSION_ID),
    CONSTRAINT FK_INCIDENT_USER   FOREIGN KEY (REPORTED_BY)  REFERENCES USERS(USER_ID),
    CONSTRAINT FK_INCIDENT_STAFF   FOREIGN KEY (RESOLVED_BY)  REFERENCES USERS(USER_ID),
    CONSTRAINT FK_INCIDENT_PAYMENT   FOREIGN KEY (PAYMENT_ID)  REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE SLOT_STATUS_LOGS (
    log_id VARCHAR(50) NOT NULL,
    slot_id VARCHAR(20) NOT NULL,
    old_status VARCHAR(20) NOT NULL,
    new_status VARCHAR(20) NOT NULL,
    changed_by VARCHAR(50) NOT NULL,
    changed_at DATETIME NOT NULL,
    reason VARCHAR(255) NULL,
    estimated_duration_minutes INT NULL,
    CONSTRAINT pk_slot_status_logs PRIMARY KEY (log_id)
);

CREATE TABLE ROLE_AUDIT_LOG (
    ROLE_LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID VARCHAR(36) NOT NULL,                 -- Ai là người đổi?
    TARGET_USER_ID VARCHAR(36) NOT NULL,            -- Đổi của ai?
    OLD_ROLE_ID INT,                                -- Quyền cũ là gì?
    NEW_ROLE_ID INT NOT NULL,                       -- Quyền mới là gì?
    CHANGED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,  -- Đổi khi nào?
    
    CONSTRAINT FK_AUDIT_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_AUDIT_TARGET FOREIGN KEY (TARGET_USER_ID) REFERENCES USERS(USER_ID)
);

-- ============================================================
-- NHÓM 8: CẤU HÌNH HỆ THỐNG
-- ============================================================

CREATE TABLE SYSTEM_SETTING (
    SETTING_ID INT AUTO_INCREMENT PRIMARY KEY,
    SETTING_KEY VARCHAR(100) NOT NULL UNIQUE,
    SETTING_VALUE TEXT NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    UPDATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SYSTEM_LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_LEVEL VARCHAR(50) NOT NULL,
    MESSAGE TEXT NOT NULL,
    SOURCE VARCHAR(150) NULL,
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- NHÓM 9: FEEDBACK
-- ============================================================

CREATE TABLE FEEDBACK (
    FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(36),                        -- Được quyền null do có khách vãng lai, không đăng kí
    FULL_NAME VARCHAR(100) NOT NULL,
    ID_CARD_NUMBER VARCHAR(20) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    STATUS ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') DEFAULT 'OPEN',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    RESOLVED_AT DATETIME,
    RESOLVED_BY VARCHAR(36),                    
    RESPONSE_NOTE TEXT NULL,

    CONSTRAINT FK_FEEDBACK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_FEEDBACK_RESOLVER FOREIGN KEY (RESOLVED_BY) REFERENCES USERS(USER_ID)
);